language: generic
sudo: required
services:
    - docker
before_install:
    - docker build sheoranpranava91/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true sheoranpranava91/react-test npm test -- --coverage
after_success:
    - docker build -t sheoranpranava91/multi-client ./client
    - docker build -t sheoranpranava91/multi-nginx ./nginx
    - docker build -t sheoranpranava91/multi-server ./server
    - docker build -t sheoranpranava91/multi-worker ./worker
# Log into docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push the image to docker hub
    - docker push sheoranpranava91/multi-client
    - docker push sheoranpranava91/multi-nginx
    - docker push sheoranpranava91/multi-server
    - docker push sheoranpranava91/multi-worker